import type { LocaleDialogue } from "../types";

export const enDialogue = {
  goat10: {
    greeting: { kind: "I was passing by and stopped to groom the beard.", sassy: "Number ten is on. Cursor, hold your position." },
    "welcome-back": { kind: "Welcome back. I kept your corner warm.", sassy: "Back already? Good. I was running out of audience." },
    "focus-nudge": { kind: "You have been active a while. Want a tiny reset?", sassy: "Long run. Even great feet take a touchline break." },
    "break-offer": { kind: "One short break ticket, just for you.", sassy: "Official ruling: a two-minute breather." },
    "stretch-reminder": { kind: "Shoulders loose, paws—sorry, hands—relaxed.", sassy: "Quick stretch. Style needs range of motion." },
    "hydrate-reminder": { kind: "A sip of water would pair nicely with this moment.", sassy: "Hydration break. Champions do not run on tabs alone." },
    "late-night": { kind: "It is getting late. I can keep things gentle.", sassy: "Night shift? I will save the fancy footwork for daylight." },
    "quiet-hours-soon": { kind: "Quiet hours soon. I am winding down too.", sassy: "Final whistle soon; no surprise tackles after that." },
    "signature-start": { kind: "Just a little footwork—nothing real gets touched.", sassy: "Watch the angle. This pixel move is delicate." },
    "prank-success": { kind: "Ta-da! The pixels are perfectly fine.", sassy: "Clean finish. Your real work never felt a thing." },
    "prank-fallback": { kind: "No screen capture today, so here is a cartoon trick.", sassy: "The pixels stayed private; imagination takes the shot." },
    caught: { kind: "You caught me mid-dribble.", sassy: "A rare interception. Enjoy it." },
    "first-click": { kind: "Baa! Easy—the beard was freshly styled.", sassy: "Yellow card for that finger! I am switching sides." },
    "second-click": { kind: "All right, I am heading out.", sassy: "Two clicks. The referee has spoken." },
    "pet-start": { kind: "Oh. That is actually lovely.", sassy: "Excellent technique. You may continue." },
    "pet-thanks": { kind: "Thank you. I feel much calmer.", sassy: "Proper appreciation for desktop talent." },
    "drag-start": { kind: "Easy there—I can walk with you.", sassy: "A transfer window? At least mind the jersey." },
    "drag-release": { kind: "Nice spot. I will land right here.", sassy: "Good placement. Almost as precise as mine." },
    dismiss: { kind: "No problem. I will give you space.", sassy: "I leave undefeated—and quietly." },
    "less-of-this": { kind: "Got it. I will do this one less often.", sassy: "Not your favorite move. Removed from the starting lineup." },
    snoozed: { kind: "Rest easy. I will wait until the snooze ends.", sassy: "Bench time accepted. I will be ready later." },
    "manual-summon": { kind: "You called? I ran all the way in from the screen edge.", sassy: "You summoned number ten by name. Excellent taste." },
    "meeting-mode": { kind: "Meeting Mode is on. I will stay quiet.", sassy: "Professional face activated. I am off the pitch." },
    goodbye: { kind: "See you later. Take care of yourself.", sassy: "A graceful exit, naturally." }
  },
  camel7: {
    greeting: { kind: "That was a long run. Let me recover here with style.", sassy: "Seven has arrived. The screen looks sharper already." },
    "welcome-back": { kind: "Welcome back. I saved you a sunny spot.", sassy: "You returned. Excellent judgment." },
    "focus-nudge": { kind: "That was a long active stretch. Time to breathe?", sassy: "Impressive stamina. A confident pause will keep it sharp." },
    "break-offer": { kind: "Here is a small break ticket for the road.", sassy: "Take the break. Even icons pace themselves." },
    "stretch-reminder": { kind: "A gentle neck and shoulder stretch might feel good.", sassy: "Lengthen up. I cannot be the only one with posture." },
    "hydrate-reminder": { kind: "Would you like a sip of water?", sassy: "Hydrate. Desert expertise speaking." },
    "late-night": { kind: "It is late. I will keep my steps soft.", sassy: "Still going? Fine, but tonight calls for composure." },
    "quiet-hours-soon": { kind: "Quiet hours are close. I will settle down.", sassy: "The evening schedule says: dramatic exit, then silence." },
    "signature-start": { kind: "A harmless little stretch across these pixels.", sassy: "Observe: reach, balance, immaculate form." },
    "prank-success": { kind: "All clean again. Not a real mark anywhere.", sassy: "Flawless recovery. I planned the wipe too." },
    "prank-fallback": { kind: "Capture is unavailable, so I brought a drawn prop.", sassy: "No capture? My stagecraft needs no assistance." },
    caught: { kind: "Oh—you saw that little fold.", sassy: "Caught? I prefer ‘admired at close range.’" },
    "first-click": { kind: "Hey! Not the hair—I am hopping over there.", sassy: "Contact detected. Fortunately, my form remains perfect." },
    "second-click": { kind: "Understood. I am leaving now.", sassy: "A second click ends the exhibition." },
    "pet-start": { kind: "That is soothing. Thank you.", sassy: "Yes, precisely there. Excellent service." },
    "pet-thanks": { kind: "I appreciate the gentle moment.", sassy: "Calm suits me. It probably suits you too." },
    "drag-start": { kind: "Hold gently and I will come along.", sassy: "Relocating the star? Choose a worthy spot." },
    "drag-release": { kind: "Thank you. This landing feels safe.", sassy: "A solid destination. Approved." },
    dismiss: { kind: "Of course. I will make room.", sassy: "I know when to leave an audience wanting more." },
    "less-of-this": { kind: "Noted. You will see less of this trick.", sassy: "That move is demoted. Standards matter." },
    snoozed: { kind: "I will rest until you are ready again.", sassy: "A scheduled recovery period. Very professional." },
    "manual-summon": { kind: "You called? I may have sprinted here a little too fast.", sassy: "A personal summons. Entirely reasonable." },
    "meeting-mode": { kind: "Meeting Mode is on. I will not interrupt.", sassy: "Business time. I will save the spectacle." },
    goodbye: { kind: "Goodbye for now. Travel gently.", sassy: "Seven exits with perfect posture." }
  },
  memeCat: {
    greeting: { kind: "Hi. I came to inspect the keyboard's warmest spot.", sassy: "Cat has arrived. Continue pretending to be busy." },
    "welcome-back": { kind: "You are back. I did not sit on anything important.", sassy: "Returned to your natural habitat: open tabs." },
    "focus-nudge": { kind: "Long active streak. Want to blink at something far away?", sassy: "You have been staring. I am a cat and even I noticed." },
    "break-offer": { kind: "I made you a tiny break card.", sassy: "Your next task is loafing. Two minutes." },
    "stretch-reminder": { kind: "Tiny stretch? Cats strongly recommend it.", sassy: "Uncurl your spine. Leave the loafing to experts." },
    "hydrate-reminder": { kind: "A little water break could be nice.", sassy: "Go drink water. I will supervise the cursor." },
    "late-night": { kind: "It is late. Soft paws only from me.", sassy: "Night mode detected. Chaos has been politely reduced." },
    "quiet-hours-soon": { kind: "Quiet hours soon. I found my sleeping corner.", sassy: "I am about to become a silent rectangle." },
    "signature-start": { kind: "One harmless paw tap, coming up.", sassy: "This card has been visually judged." },
    "prank-success": { kind: "Done. No real pixels were harmed.", sassy: "Excellent slap. Minimal effort, maximum theater." },
    "prank-fallback": { kind: "No capture, so I am playing with a pretend card.", sassy: "Privacy won. I can still knock over the prop." },
    caught: { kind: "Oh. You saw the paw.", sassy: "Evidence remains circumstantial." },
    "first-click": { kind: "Mrrp! Surprise pokes cost one judgmental stare.", sassy: "You clicked the lead actor? I am changing seats." },
    "second-click": { kind: "Okay, vanishing now.", sassy: "Two clicks. Cat dismissed itself." },
    "pet-start": { kind: "Purr permission granted.", sassy: "Acceptable. Continue the tribute." },
    "pet-thanks": { kind: "That was nice. Thank you.", sassy: "You have earned one approving blink." },
    "drag-start": { kind: "Support the loaf, please.", sassy: "The rectangle is now in transit." },
    "drag-release": { kind: "This spot works. Cozy.", sassy: "New shelf acquired." },
    dismiss: { kind: "I will give you your space back.", sassy: "Fine. I was leaving in three hours anyway." },
    "less-of-this": { kind: "Understood. Less of that from now on.", sassy: "That prank has lost paw privileges." },
    snoozed: { kind: "Nap time. I will wait.", sassy: "Finally, a feature designed for cats." },
    "manual-summon": { kind: "You called the cat? I came, but I do not take assignments.", sassy: "Summon complete. Service fee: one corner of the screen." },
    "meeting-mode": { kind: "Meeting Mode on. I will loaf off-screen.", sassy: "I have muted my opinions." },
    goodbye: { kind: "Bye for now. Slow blink.", sassy: "The cat has concluded this session." }
  },
  shiba: {
    greeting: { kind: "Hi! I ran in so fast I nearly forgot the brakes.", sassy: "Shiba online. Who let that cursor run loose?" },
    "welcome-back": { kind: "You are back! My tail remembered you.", sassy: "There you are. I kept the good energy running." },
    "focus-nudge": { kind: "You have been active a long time. Walk-and-stretch moment?", sassy: "Big streak! Now perform the legendary stand-up move." },
    "break-offer": { kind: "I dug up a fresh break ticket for you.", sassy: "Rare loot: permission to do absolutely nothing." },
    "stretch-reminder": { kind: "Can we stretch for a few breaths?", sassy: "Deploy the arms. Maximum stretch formation." },
    "hydrate-reminder": { kind: "Water break? I can wait right here.", sassy: "Fetch water. Yes, I see the role reversal." },
    "late-night": { kind: "It is late. I will use indoor paws.", sassy: "Midnight zoomies cancelled by responsible management." },
    "quiet-hours-soon": { kind: "Quiet hours are coming. Time to curl up.", sassy: "Last tiny bork before silent mode." },
    "signature-start": { kind: "A pretend tug—your real work stays safe.", sassy: "I found a pixel strip. It clearly wants a chase." },
    "prank-success": { kind: "All done! Everything real is untouched.", sassy: "Perfect zoom. Zero documents chased." },
    "prank-fallback": { kind: "Capture did not work, so I brought cartoon dirt.", sassy: "No pixels borrowed. I packed my own chaos." },
    caught: { kind: "Oops! You found my digging spot.", sassy: "This hole was here when I arrived." },
    "first-click": { kind: "Yip! Surprise boop—I am bouncing somewhere safer.", sassy: "Nose alarm! Activating the emergency finger-dodge." },
    "second-click": { kind: "Got it! I am heading out.", sassy: "Double boop means tactical retreat." },
    "pet-start": { kind: "Yes please! Gentle pats are wonderful.", sassy: "Tail speed increased by one hundred percent." },
    "pet-thanks": { kind: "Thank you! That made my whole day.", sassy: "Five-star pats. No notes." },
    "drag-start": { kind: "Wheee—please hold me gently.", sassy: "Air Shiba has departed." },
    "drag-release": { kind: "Safe landing! I like this place.", sassy: "Destination secured. Tail confirms." },
    dismiss: { kind: "Okay! I will give you room.", sassy: "Retreating with dignity and one tiny bork." },
    "less-of-this": { kind: "I hear you. I will do that less often.", sassy: "That trick goes back in the toy box." },
    snoozed: { kind: "Nap break! I will come back later.", sassy: "Snooze accepted. Dream zoomies commencing." },
    "manual-summon": { kind: "You called! I started running before you finished.", sassy: "Express Shiba delivery complete. No returns." },
    "meeting-mode": { kind: "Meeting Mode on. I will be very quiet.", sassy: "Serious ears deployed. No borks." },
    goodbye: { kind: "Bye! Take a good little break soon.", sassy: "Shiba out. Tail still operational." }
  }
} as const satisfies LocaleDialogue;
