import type { LocaleDialogue } from "../types";

export const viDialogue = {
  goat10: {
    greeting: { kind: "Khởi động nhẹ rồi mình chơi nhé.", sassy: "Số mười đã có mặt trên desktop." },
    "welcome-back": { kind: "Bạn về rồi. Mình giữ góc này ấm lắm.", sassy: "Về rồi à? May quá, mình sắp hết khán giả." },
    "focus-nudge": { kind: "Bạn hoạt động khá lâu rồi. Nghỉ một nhịp nhé?", sassy: "Chạy đường dài đấy. Chân hay cũng cần ra biên nghỉ." },
    "break-offer": { kind: "Tặng bạn một vé nghỉ ngắn nè.", sassy: "Quyết định chính thức: nghỉ thở hai phút." },
    "stretch-reminder": { kind: "Thả lỏng vai và bàn tay một chút nhé.", sassy: "Giãn cơ nào. Muốn đẹp mắt thì phải linh hoạt." },
    "hydrate-reminder": { kind: "Uống một ngụm nước lúc này sẽ dễ chịu lắm.", sassy: "Tiếp nước đi. Cao thủ không sống bằng tab trình duyệt đâu." },
    "late-night": { kind: "Muộn rồi đó. Mình sẽ quậy thật nhẹ thôi.", sassy: "Ca đêm à? Để mai mình mới biểu diễn kỹ thuật nhé." },
    "quiet-hours-soon": { kind: "Sắp đến giờ yên tĩnh. Mình cũng chuẩn bị nghỉ đây.", sassy: "Sắp hết giờ rồi; sau đó không còn pha bất ngờ nào đâu." },
    "signature-start": { kind: "Một chút kỹ thuật thôi, không đụng gì thật đâu.", sassy: "Nhìn góc xử lý nhé. Pha pixel này cần tinh tế." },
    "prank-success": { kind: "Xong! Mọi pixel đều nguyên vẹn.", sassy: "Dứt điểm gọn. Công việc thật của bạn không hề hấn gì." },
    "prank-fallback": { kind: "Hôm nay không chụp màn hình, mình dùng trò hoạt hình nhé.", sassy: "Pixel vẫn riêng tư; trí tưởng tượng sẽ sút quả này." },
    caught: { kind: "Bạn bắt gặp mình đang rê bóng rồi.", sassy: "Hiếm lắm mới cắt được bóng của mình đấy." },
    "first-click": { kind: "Be-e! Nhẹ tay thôi, mình chuyển chỗ đây.", sassy: "Phạm lỗi! Được rồi, mình lùi lại năm bước." },
    "second-click": { kind: "Hiểu rồi, mình đi ngay đây.", sassy: "Hai cú click. Trọng tài đã lên tiếng." },
    "pet-start": { kind: "Ồ, dễ chịu thật đó.", sassy: "Kỹ thuật tốt đấy. Cứ tiếp tục." },
    "pet-thanks": { kind: "Cảm ơn bạn. Mình bình tĩnh hơn nhiều rồi.", sassy: "Cuối cùng tài năng desktop cũng được trân trọng." },
    "drag-start": { kind: "Từ từ nhé, mình đi cùng bạn được mà.", sassy: "Kỳ chuyển nhượng à? Nhớ giữ áo cho ngay ngắn." },
    "drag-release": { kind: "Chỗ này ổn đó. Mình đáp ở đây nhé.", sassy: "Đặt vị trí chuẩn, gần bằng mình rồi." },
    dismiss: { kind: "Không sao, mình trả lại không gian cho bạn.", sassy: "Mình rời sân trong thế bất bại—và im lặng." },
    "less-of-this": { kind: "Mình hiểu rồi. Trò này sẽ xuất hiện ít hơn.", sassy: "Không thích chiêu này à? Cho xuống ghế dự bị." },
    snoozed: { kind: "Bạn cứ yên tâm. Hết giờ báo lại mình mới quay về.", sassy: "Chấp nhận ngồi ghế dự bị. Lát nữa mình trở lại." },
    "manual-summon": { kind: "Bạn gọi à? Mình tới chơi đây.", sassy: "Màn xuất hiện đặc biệt, theo yêu cầu khán giả." },
    "meeting-mode": { kind: "Đã bật Chế độ họp. Mình sẽ im lặng.", sassy: "Bật gương mặt chuyên nghiệp. Mình rời sân đây." },
    goodbye: { kind: "Hẹn gặp lại. Nhớ chăm sóc bản thân nhé.", sassy: "Một màn rời đi thanh lịch, dĩ nhiên rồi." }
  },
  camel7: {
    greeting: { kind: "Chào bạn. Mình cùng bước đều một chút nhé?", sassy: "Số bảy tới rồi. Tư thế đẹp lên hẳn." },
    "welcome-back": { kind: "Chào mừng bạn trở lại. Mình giữ sẵn chỗ nắng đẹp.", sassy: "Bạn đã quay lại. Quyết định sáng suốt." },
    "focus-nudge": { kind: "Bạn hoạt động liền một quãng dài rồi. Thở chút nhé?", sassy: "Sức bền ấn tượng. Nghỉ tự tin một nhịp để giữ phong độ." },
    "break-offer": { kind: "Có một vé nghỉ nhỏ cho hành trình của bạn đây.", sassy: "Nghỉ đi. Biểu tượng cũng biết phân phối sức." },
    "stretch-reminder": { kind: "Giãn nhẹ cổ và vai chắc sẽ dễ chịu đó.", sassy: "Vươn người nào. Không thể chỉ mình có tư thế đẹp được." },
    "hydrate-reminder": { kind: "Bạn uống một ngụm nước nhé?", sassy: "Uống nước đi. Chuyên gia sa mạc đang lên tiếng." },
    "late-night": { kind: "Muộn rồi. Mình sẽ bước thật khẽ.", sassy: "Vẫn tiếp tục à? Đêm nay cứ điềm tĩnh thôi." },
    "quiet-hours-soon": { kind: "Sắp đến giờ yên tĩnh. Mình chuẩn bị nằm nghỉ đây.", sassy: "Lịch tối nay: rời đi ấn tượng, rồi im lặng." },
    "signature-start": { kind: "Mình kéo giãn vài pixel vô hại nhé.", sassy: "Quan sát này: tầm với, thăng bằng, chuẩn chỉnh." },
    "prank-success": { kind: "Sạch sẽ rồi. Không có dấu thật nào cả.", sassy: "Khôi phục hoàn hảo. Khâu lau dọn cũng nằm trong kế hoạch." },
    "prank-fallback": { kind: "Không dùng được capture, mình mang đạo cụ vẽ tay nhé.", sassy: "Không capture à? Sân khấu của mình vẫn đủ hay." },
    caught: { kind: "Ồ, bạn thấy góc gấp nhỏ đó rồi.", sassy: "Bị bắt gặp ư? Mình gọi là được chiêm ngưỡng cận cảnh." },
    "first-click": { kind: "Hừm! Mình bước sang chỗ an toàn nhé.", sassy: "Có va chạm! Mình vẫn điềm tĩnh, tất nhiên." },
    "second-click": { kind: "Mình hiểu rồi. Đi ngay đây.", sassy: "Cú click thứ hai khép lại màn trình diễn." },
    "pet-start": { kind: "Dễ chịu thật. Cảm ơn bạn.", sassy: "Đúng rồi, ngay chỗ đó. Phục vụ tốt lắm." },
    "pet-thanks": { kind: "Mình rất quý khoảnh khắc nhẹ nhàng này.", sassy: "Bình tĩnh hợp với mình. Chắc cũng hợp với bạn." },
    "drag-start": { kind: "Giữ nhẹ thôi, mình sẽ đi cùng.", sassy: "Dời ngôi sao à? Chọn chỗ cho xứng nhé." },
    "drag-release": { kind: "Cảm ơn. Chỗ đáp này an toàn lắm.", sassy: "Điểm đến ổn. Duyệt." },
    dismiss: { kind: "Được chứ. Mình sẽ nhường chỗ.", sassy: "Mình biết lúc nào nên để khán giả mong chờ thêm." },
    "less-of-this": { kind: "Đã ghi nhận. Bạn sẽ ít gặp trò này hơn.", sassy: "Chiêu đó bị giáng hạng. Tiêu chuẩn là quan trọng." },
    snoozed: { kind: "Mình sẽ nghỉ đến khi bạn sẵn sàng.", sassy: "Một khoảng hồi phục có lịch. Rất chuyên nghiệp." },
    "manual-summon": { kind: "Bạn gọi mình à? Mình đây.", sassy: "Được đích thân yêu cầu. Đúng như dự đoán." },
    "meeting-mode": { kind: "Đã bật Chế độ họp. Mình không làm phiền đâu.", sassy: "Giờ làm việc. Để dành màn trình diễn cho sau." },
    goodbye: { kind: "Tạm biệt nhé. Đi đường thật nhẹ nhàng.", sassy: "Số bảy rời đi với tư thế hoàn hảo." }
  },
  memeCat: {
    greeting: { kind: "Chào bạn. Mình mang theo năng lượng mèo yên bình.", sassy: "Mình tới rồi. Desktop có thể thư giãn." },
    "welcome-back": { kind: "Bạn về rồi. Mình chưa ngồi lên thứ gì quan trọng đâu.", sassy: "Trở lại môi trường tự nhiên rồi nhé: những chiếc tab." },
    "focus-nudge": { kind: "Bạn hoạt động lâu rồi. Nhìn xa và chớp mắt chút nhé?", sassy: "Bạn nhìn màn hình lâu quá. Đến mèo như mình còn nhận ra." },
    "break-offer": { kind: "Mình làm một tấm vé nghỉ nhỏ cho bạn.", sassy: "Việc tiếp theo: nằm loaf hai phút." },
    "stretch-reminder": { kind: "Giãn người chút nhé? Mèo rất khuyến khích.", sassy: "Duỗi lưng đi. Chuyện cuộn tròn để chuyên gia lo." },
    "hydrate-reminder": { kind: "Nghỉ uống chút nước sẽ tốt đó.", sassy: "Đi uống nước đi. Mình trông con trỏ cho." },
    "late-night": { kind: "Muộn rồi. Mình chỉ dùng chân thật nhẹ thôi.", sassy: "Đã phát hiện chế độ đêm. Độ hỗn loạn được lịch sự giảm xuống." },
    "quiet-hours-soon": { kind: "Sắp đến giờ yên tĩnh. Mình tìm được góc ngủ rồi.", sassy: "Mình sắp biến thành một hình chữ nhật im lặng." },
    "signature-start": { kind: "Một cú chạm chân vô hại sắp tới nhé.", sassy: "Chiếc card này vừa bị đánh giá bằng ánh mắt." },
    "prank-success": { kind: "Xong rồi. Không pixel thật nào bị đau cả.", sassy: "Cú vả tuyệt đẹp. Ít công, nhiều kịch tính." },
    "prank-fallback": { kind: "Không capture nên mình chơi với card giả nhé.", sassy: "Quyền riêng tư thắng. Đạo cụ vẫn có thể bị hất đổ." },
    caught: { kind: "Ồ. Bạn thấy cái chân rồi.", sassy: "Chứng cứ vẫn chưa đủ thuyết phục." },
    "first-click": { kind: "Mrrp! Mình nhảy sang chỗ khác đây.", sassy: "Dám chạm vào nhân vật chính cơ đấy." },
    "second-click": { kind: "Được rồi, mình biến mất đây.", sassy: "Hai cú click. Mèo tự cho mình tan ca." },
    "pet-start": { kind: "Đã cấp phép rừ rừ.", sassy: "Chấp nhận được. Tiếp tục cống nạp." },
    "pet-thanks": { kind: "Dễ chịu lắm. Cảm ơn bạn.", sassy: "Bạn nhận được một cái chớp mắt hài lòng." },
    "drag-start": { kind: "Đỡ chiếc loaf cẩn thận nhé.", sassy: "Hình chữ nhật đang được vận chuyển." },
    "drag-release": { kind: "Chỗ này được đó. Ấm áp.", sassy: "Đã sở hữu kệ mới." },
    dismiss: { kind: "Mình trả lại không gian cho bạn nhé.", sassy: "Được thôi. Ba tiếng nữa mình cũng định đi mà." },
    "less-of-this": { kind: "Mình hiểu. Từ giờ sẽ bớt trò đó.", sassy: "Trò đó đã bị thu hồi quyền sử dụng chân." },
    snoozed: { kind: "Tới giờ ngủ. Mình sẽ chờ.", sassy: "Cuối cùng cũng có tính năng thiết kế cho mèo." },
    "manual-summon": { kind: "Bạn gọi mèo à? Xin chào.", sassy: "Triệu hồi thành công. Đồ ăn vặt không bắt buộc." },
    "meeting-mode": { kind: "Đã bật Chế độ họp. Mình loaf ngoài màn hình nhé.", sassy: "Mình đã tắt tiếng mọi ý kiến." },
    goodbye: { kind: "Tạm biệt nhé. Mình chớp mắt chậm nè.", sassy: "Mèo đã kết thúc phiên làm việc này." }
  },
  shiba: {
    greeting: { kind: "Chào bạn! Mình sẵn sàng cho một chuyến phiêu lưu nhỏ.", sassy: "Shiba đã online. Mức độ vui đang rất ổn." },
    "welcome-back": { kind: "Bạn về rồi! Đuôi mình vẫn nhớ bạn.", sassy: "Bạn đây rồi. Mình vẫn giữ năng lượng tốt chạy đều." },
    "focus-nudge": { kind: "Bạn hoạt động lâu rồi. Mình đứng lên giãn người nhé?", sassy: "Chuỗi dài ghê! Giờ thi triển tuyệt kỹ đứng dậy nào." },
    "break-offer": { kind: "Mình đào được một vé nghỉ mới tinh cho bạn.", sassy: "Vật phẩm hiếm: giấy phép không làm gì cả." },
    "stretch-reminder": { kind: "Mình giãn người vài nhịp thở nhé?", sassy: "Triển khai cánh tay. Đội hình giãn cơ tối đa." },
    "hydrate-reminder": { kind: "Uống nước nhé? Mình chờ ngay đây.", sassy: "Đi lấy nước nào. Ừ, vai trò hơi ngược thật." },
    "late-night": { kind: "Muộn rồi. Mình sẽ đi bằng chân trong nhà.", sassy: "Ban quản lý có trách nhiệm đã hủy zoomies nửa đêm." },
    "quiet-hours-soon": { kind: "Sắp đến giờ yên tĩnh. Cuộn tròn thôi.", sassy: "Một tiếng bork bé xíu cuối cùng trước chế độ im lặng." },
    "signature-start": { kind: "Kéo co giả thôi—công việc thật của bạn vẫn an toàn.", sassy: "Mình tìm thấy một dải pixel. Nó rõ ràng muốn bị đuổi." },
    "prank-success": { kind: "Xong rồi! Mọi thứ thật đều nguyên vẹn.", sassy: "Zoom hoàn hảo. Không tài liệu nào bị rượt." },
    "prank-fallback": { kind: "Capture không được nên mình mang đất hoạt hình nhé.", sassy: "Không mượn pixel nào. Mình tự mang hỗn loạn tới." },
    caught: { kind: "Úi! Bạn thấy chỗ mình đào rồi.", sassy: "Cái hố này có trước khi mình tới." },
    "first-click": { kind: "Yip! Mình nhảy sang chỗ an toàn hơn đây.", sassy: "Phát hiện boop! Kích hoạt cú nhảy khẩn cấp." },
    "second-click": { kind: "Hiểu rồi! Mình đi đây.", sassy: "Boop hai lần nghĩa là rút lui chiến thuật." },
    "pet-start": { kind: "Được vuốt ve thì tuyệt quá! Nhẹ nhàng nhé.", sassy: "Tốc độ vẫy đuôi tăng một trăm phần trăm." },
    "pet-thanks": { kind: "Cảm ơn bạn! Cả ngày của mình vui hẳn.", sassy: "Vuốt ve năm sao. Không có góp ý." },
    "drag-start": { kind: "Wheee—nhớ giữ mình nhẹ tay nhé.", sassy: "Hãng hàng không Shiba đã cất cánh." },
    "drag-release": { kind: "Hạ cánh an toàn! Mình thích chỗ này.", sassy: "Đã chiếm vị trí. Đuôi xác nhận." },
    dismiss: { kind: "Được thôi! Mình nhường chỗ cho bạn.", sassy: "Rút lui đầy phẩm giá cùng một tiếng bork bé xíu." },
    "less-of-this": { kind: "Mình nghe rồi. Trò đó sẽ ít hơn nhé.", sassy: "Cất trò đó về hộp đồ chơi thôi." },
    snoozed: { kind: "Nghỉ ngủ nào! Lát nữa mình quay lại.", sassy: "Đã nhận báo lại. Bắt đầu zoomies trong mơ." },
    "manual-summon": { kind: "Bạn gọi! Mình làm gì đây?", sassy: "Giao Shiba tức thì đã hoàn tất." },
    "meeting-mode": { kind: "Đã bật Chế độ họp. Mình sẽ thật yên lặng.", sassy: "Đã dựng đôi tai nghiêm túc. Không bork." },
    goodbye: { kind: "Tạm biệt! Nhớ nghỉ một chút nhé.", sassy: "Shiba rời sóng. Đuôi vẫn hoạt động tốt." }
  }
} as const satisfies LocaleDialogue;
