import type { LocaleDialogue } from "../types";

export const viDialogue = {
  goat10: {
    greeting: { kind: "Mình đi ngang, tiện ghé vuốt râu một cái.", sassy: "Số 10 vào sân. Con trỏ nhớ giữ đúng vị trí." },
    "welcome-back": { kind: "Bạn về rồi. Mình vừa trông màn hình hộ đấy.", sassy: "Về rồi à? Tốt, mình diễn một mình hơi phí." },
    "focus-nudge": { kind: "Bạn cày hơi lâu rồi. Đổi hiệp bằng một ngụm nước nhé?", sassy: "Chuỗi thao tác dài đấy. Ghế dự bị đang nhớ bạn." },
    "break-offer": { kind: "Vé nghỉ hai phút đây—không cần ký nhận.", sassy: "Tổ trọng tài xác nhận: bạn cần rời màn hình hai phút." },
    "stretch-reminder": { kind: "Thả vai xuống nhé, nó đâu phải đôi khuyên tai.", sassy: "Vai cao thế? Mình tưởng bạn đang phòng thủ phạt góc." },
    "hydrate-reminder": { kind: "Uống nước đi, mình giữ hộ đống thẻ trình duyệt này.", sassy: "Tiếp nước nào. Trình duyệt không tính là đồ uống." },
    "late-night": { kind: "Muộn rồi đó. Mình sẽ quậy thật nhẹ thôi.", sassy: "Ca đêm à? Để mai mình mới biểu diễn kỹ thuật nhé." },
    "quiet-hours-soon": { kind: "Sắp đến giờ yên tĩnh. Mình cũng chuẩn bị nghỉ đây.", sassy: "Sắp hết giờ rồi; sau đó không còn pha bất ngờ nào đâu." },
    "signature-start": { kind: "Cho mình mượn vài điểm ảnh làm đạo cụ nhé—trả nguyên vẹn.", sassy: "Im nào, mình đang xử lý pha bóng giữa hai cửa sổ." },
    "prank-success": { kind: "Xong! Không điểm ảnh nào phải gọi bảo hiểm.", sassy: "Gọn như pha chiếu lại. Công việc thật vẫn còn nguyên, tiếc ghê." },
    "prank-fallback": { kind: "Không chụp được màn hình, mình diễn chay vẫn vui.", sassy: "Quyền chụp màn hình từ chối. Tài năng thì không." },
    caught: { kind: "Ơ, bạn thấy mình gặm góc màn hình à?", sassy: "Bắt quả tang rồi. Nhưng bằng chứng chỉ là điểm ảnh." },
    "first-click": { kind: "Be-e! Chạm nhẹ thôi, râu mình vừa chải xong.", sassy: "Thẻ vàng cho ngón tay! Mình nhảy chỗ khác đây." },
    "second-click": { kind: "Hiểu rồi, mình đi ngay đây.", sassy: "Hai lần bấm. Trọng tài đã lên tiếng." },
    "pet-start": { kind: "Ồ, dễ chịu thật đó.", sassy: "Kỹ thuật tốt đấy. Cứ tiếp tục." },
    "pet-thanks": { kind: "Ừm, đúng chỗ ngứa luôn. Cảm ơn nhé.", sassy: "Được, tha lỗi cú bấm vừa rồi. Vuốt tiếp đi." },
    "drag-start": { kind: "Từ từ nhé, mình đi cùng bạn được mà.", sassy: "Kỳ chuyển nhượng à? Nhớ giữ áo cho ngay ngắn." },
    "drag-release": { kind: "Chỗ này ổn đó. Góc nhìn đẹp, râu đủ sáng.", sassy: "Đặt vị trí khá chuẩn. Mình chấm tám rưỡi." },
    dismiss: { kind: "Không sao, mình trả lại không gian cho bạn.", sassy: "Mình rời sân trong thế bất bại—và im lặng." },
    "less-of-this": { kind: "Mình hiểu rồi. Trò này sẽ xuất hiện ít hơn.", sassy: "Không thích chiêu này à? Cho xuống ghế dự bị." },
    snoozed: { kind: "Bạn cứ yên tâm. Hết giờ báo lại mình mới quay về.", sassy: "Chấp nhận ngồi ghế dự bị. Lát nữa mình trở lại." },
    "manual-summon": { kind: "Bạn gọi à? Mình chạy từ mép màn hình tới đây.", sassy: "Triệu hồi đích danh số 10—gu tốt đấy." },
    "meeting-mode": { kind: "Đã bật Chế độ họp. Mình sẽ im lặng.", sassy: "Bật gương mặt chuyên nghiệp. Mình rời sân đây." },
    goodbye: { kind: "Hẹn gặp lại. Nhớ chăm sóc bản thân nhé.", sassy: "Một màn rời đi thanh lịch, dĩ nhiên rồi." }
  },
  camel7: {
    greeting: { kind: "Mình chạy hơi xa, cho đứng đây lấy lại phong độ nhé.", sassy: "Số 7 xuất hiện. Ánh sáng màn hình vừa đẹp hơn." },
    "welcome-back": { kind: "Bạn quay lại rồi. Mình giữ sẵn một góc không dính cát.", sassy: "Cuối cùng cũng về. Màn hình thiếu thần thái hẳn." },
    "focus-nudge": { kind: "Bạn thao tác lâu rồi. Cổ dài như mình cũng phải nghỉ đấy.", sassy: "Sức bền khá. Nhưng dáng ngồi đang xin thay người." },
    "break-offer": { kind: "Nghỉ hai phút nhé. Sa mạc vẫn chờ được mà.", sassy: "Lệnh từ số 7: đứng dậy trước khi chiếc ghế thắng bạn." },
    "stretch-reminder": { kind: "Vươn vai chút nhé. Mình làm mẫu phần cổ.", sassy: "Duỗi người nào. Tư thế hiện tại chưa đủ lên poster." },
    "hydrate-reminder": { kind: "Uống nước đi. Lời khuyên này có chuyên môn sa mạc.", sassy: "Ly nước ở đâu? Đừng bắt lạc đà phải nhắc lần hai." },
    "late-night": { kind: "Muộn rồi. Mình sẽ bước thật khẽ.", sassy: "Vẫn tiếp tục à? Đêm nay cứ điềm tĩnh thôi." },
    "quiet-hours-soon": { kind: "Sắp đến giờ yên tĩnh. Mình chuẩn bị nằm nghỉ đây.", sassy: "Lịch tối nay: rời đi ấn tượng, rồi im lặng." },
    "signature-start": { kind: "Mình kéo dải điểm ảnh một chút rồi gấp lại ngay.", sassy: "Đừng chớp mắt. Màn đáp đất này có điểm kỹ thuật." },
    "prank-success": { kind: "Xong rồi. Màn hình sạch hơn lòng tự trọng của mình.", sassy: "Hoàn hảo. Cả phá lẫn dọn đều có phong cách." },
    "prank-fallback": { kind: "Chụp màn hình đang bận, mình dùng đạo cụ tự mang theo.", sassy: "Không cần ảnh màn hình vẫn diễn được. Đó gọi là đẳng cấp." },
    caught: { kind: "Bạn thấy mình nhai góc giả rồi à?", sassy: "Không phải bị bắt gặp—là cho xem hậu trường." },
    "first-click": { kind: "Ối! Đừng chạm vào kiểu tóc, mình nhảy đây.", sassy: "Có tiếp xúc! May là phong độ không suy suyển." },
    "second-click": { kind: "Mình hiểu rồi. Đi ngay đây.", sassy: "Lần bấm thứ hai khép lại màn trình diễn." },
    "pet-start": { kind: "Dễ chịu thật. Cảm ơn bạn.", sassy: "Đúng rồi, ngay chỗ đó. Phục vụ tốt lắm." },
    "pet-thanks": { kind: "Êm thật. Cát trong đầu cũng lắng xuống rồi.", sassy: "Tay nghề ổn. Bạn được phép tiếp tục." },
    "drag-start": { kind: "Giữ nhẹ thôi, mình sẽ đi cùng.", sassy: "Dời ngôi sao à? Chọn chỗ cho xứng nhé." },
    "drag-release": { kind: "Cảm ơn. Chỗ đáp này an toàn lắm.", sassy: "Điểm đến ổn. Duyệt." },
    dismiss: { kind: "Được chứ. Mình sẽ nhường chỗ.", sassy: "Mình biết lúc nào nên để khán giả mong chờ thêm." },
    "less-of-this": { kind: "Đã ghi nhận. Bạn sẽ ít gặp trò này hơn.", sassy: "Chiêu đó bị giáng hạng. Tiêu chuẩn là quan trọng." },
    snoozed: { kind: "Mình sẽ nghỉ đến khi bạn sẵn sàng.", sassy: "Một khoảng hồi phục có lịch. Rất chuyên nghiệp." },
    "manual-summon": { kind: "Bạn gọi mình à? Mình chạy tới hơi nhanh đấy.", sassy: "Được đích thân triệu hồi. Hợp lý thôi." },
    "meeting-mode": { kind: "Đã bật Chế độ họp. Mình không làm phiền đâu.", sassy: "Giờ làm việc. Để dành màn trình diễn cho sau." },
    goodbye: { kind: "Tạm biệt nhé. Đi đường thật nhẹ nhàng.", sassy: "Số bảy rời đi với tư thế hoàn hảo." }
  },
  memeCat: {
    greeting: { kind: "Chào. Mình ghé qua kiểm tra độ ấm của bàn phím.", sassy: "Mèo đã tới. Bạn có thể tiếp tục giả vờ bận." },
    "welcome-back": { kind: "Bạn về rồi. Mình chưa ngồi lên thứ gì quan trọng đâu.", sassy: "Trở lại môi trường tự nhiên rồi nhé: những thẻ trình duyệt." },
    "focus-nudge": { kind: "Bạn nhìn màn hình lâu rồi. Chớp mắt đi, mình đếm hộ.", sassy: "Nhìn lâu quá. Đến mèo còn thấy bạn thiếu bảo trì." },
    "break-offer": { kind: "Mình cấp phép nghỉ hai phút. Dấu chân là chữ ký.", sassy: "Nhiệm vụ tiếp theo: nằm ổ bánh hai phút. Độ ưu tiên: mèo." },
    "stretch-reminder": { kind: "Giãn người chút nhé? Mèo rất khuyến khích.", sassy: "Duỗi lưng đi. Chuyện cuộn tròn để chuyên gia lo." },
    "hydrate-reminder": { kind: "Đi uống nước nhé. Mình hứa chỉ ngồi lên một thẻ trình duyệt thôi.", sassy: "Lấy nước đi. Con trỏ này giờ thuộc quyền giám sát của mèo." },
    "late-night": { kind: "Muộn rồi. Mình chỉ dùng chân thật nhẹ thôi.", sassy: "Đã phát hiện chế độ đêm. Độ hỗn loạn được lịch sự giảm xuống." },
    "quiet-hours-soon": { kind: "Sắp đến giờ yên tĩnh. Mình tìm được góc ngủ rồi.", sassy: "Mình sắp biến thành một hình chữ nhật im lặng." },
    "signature-start": { kind: "Mình thử vả nhẹ tấm thẻ giả này nhé.", sassy: "Tấm thẻ này xấu. Mình sẽ xử lý bằng chân." },
    "prank-success": { kind: "Xong rồi. Không điểm ảnh thật nào bị đau cả.", sassy: "Cú vả tuyệt đẹp. Ít công, nhiều kịch tính." },
    "prank-fallback": { kind: "Không chụp được màn hình nên mình chơi với thẻ giả nhé.", sassy: "Quyền riêng tư thắng. Đạo cụ vẫn có thể bị hất đổ." },
    caught: { kind: "Ồ. Bạn thấy chân mình ở hiện trường rồi.", sassy: "Không có luật sư mèo, mình không nói gì thêm." },
    "first-click": { kind: "Méo! Chạm bất ngờ là phụ thu một cái lườm đấy.", sassy: "Dám bấm vào nhân vật chính? Mình đổi ghế." },
    "second-click": { kind: "Được rồi, mình biến mất đây.", sassy: "Hai lần bấm. Mèo tự cho mình tan ca." },
    "pet-start": { kind: "Đã cấp phép rừ rừ.", sassy: "Chấp nhận được. Tiếp tục cống nạp." },
    "pet-thanks": { kind: "Ừm. Bạn đã được nâng cấp thành người biết vuốt mèo.", sassy: "Tạm được. Thưởng một cái chớp mắt chậm." },
    "drag-start": { kind: "Đỡ khối mèo này cẩn thận nhé.", sassy: "Hình chữ nhật đang được vận chuyển." },
    "drag-release": { kind: "Chỗ này được đó. Ấm áp.", sassy: "Đã sở hữu kệ mới." },
    dismiss: { kind: "Mình trả lại không gian cho bạn nhé.", sassy: "Được thôi. Ba tiếng nữa mình cũng định đi mà." },
    "less-of-this": { kind: "Mình hiểu. Từ giờ sẽ bớt trò đó.", sassy: "Trò đó đã bị thu hồi quyền sử dụng chân." },
    snoozed: { kind: "Tới giờ ngủ. Mình sẽ chờ.", sassy: "Cuối cùng cũng có tính năng thiết kế cho mèo." },
    "manual-summon": { kind: "Bạn gọi mèo à? Mình tới, nhưng không nhận việc.", sassy: "Triệu hồi thành công. Phí dịch vụ là một góc màn hình." },
    "meeting-mode": { kind: "Đã bật Chế độ họp. Mình nằm ổ bánh ngoài màn hình nhé.", sassy: "Mình đã tắt tiếng mọi ý kiến." },
    goodbye: { kind: "Tạm biệt nhé. Mình chớp mắt chậm nè.", sassy: "Mèo đã kết thúc phiên làm việc này." }
  },
  shiba: {
    greeting: { kind: "Chào! Mình chạy vào nhanh quá, suýt quên phanh.", sassy: "Shiba lên sóng. Ai để con trỏ chạy lung tung thế?" },
    "welcome-back": { kind: "Bạn về rồi! Đuôi mình vẫn nhớ bạn.", sassy: "Bạn đây rồi. Mình vẫn giữ năng lượng tốt chạy đều." },
    "focus-nudge": { kind: "Bạn ngồi lâu rồi. Đứng dậy chạy vòng vòng một chút nhé?", sassy: "Chuỗi thao tác dài ghê. Kỹ năng đứng dậy đang hồi chiêu xong rồi." },
    "break-offer": { kind: "Mình đào được vé nghỉ hai phút. Hơi dính đất thôi.", sassy: "Vật phẩm hiếm: giấy phép bỏ mặc màn hình hai phút." },
    "stretch-reminder": { kind: "Mình giãn người vài nhịp thở nhé?", sassy: "Triển khai cánh tay. Đội hình giãn cơ tối đa." },
    "hydrate-reminder": { kind: "Đi uống nước nhé. Mình ngồi canh nút Lưu.", sassy: "Lấy nước đi. Đúng, hôm nay chó đang nhắc người." },
    "late-night": { kind: "Muộn rồi. Mình sẽ đi bằng chân trong nhà.", sassy: "Ban quản lý có trách nhiệm đã hủy màn chạy vòng vòng nửa đêm." },
    "quiet-hours-soon": { kind: "Sắp đến giờ yên tĩnh. Cuộn tròn thôi.", sassy: "Một tiếng gâu bé xíu cuối cùng trước chế độ im lặng." },
    "signature-start": { kind: "Mình kéo dải điểm ảnh giả này nhé. Nó nhìn giống đồ chơi quá.", sassy: "Dải điểm ảnh chạy trước. Shiba không chịu trách nhiệm phần sau." },
    "prank-success": { kind: "Xong rồi! Mọi thứ thật đều nguyên vẹn.", sassy: "Zoom hoàn hảo. Không tài liệu nào bị rượt." },
    "prank-fallback": { kind: "Không chụp được màn hình nên mình mang đất hoạt hình nhé.", sassy: "Không mượn điểm ảnh nào. Mình tự mang hỗn loạn tới." },
    caught: { kind: "Úi! Bạn thấy chỗ mình đào rồi. Đừng nhìn đống đất.", sassy: "Cái hố có trước khi mình tới. Shiba tuyên bố vậy." },
    "first-click": { kind: "Áu! Chạm mũi bất ngờ—mình nhảy chỗ khác đây!", sassy: "Báo động mũi! Kích hoạt cú nhảy né ngón tay." },
    "second-click": { kind: "Hiểu rồi! Mình đi đây.", sassy: "Chạm mũi hai lần nghĩa là rút lui chiến thuật." },
    "pet-start": { kind: "Được vuốt ve thì tuyệt quá! Nhẹ nhàng nhé.", sassy: "Tốc độ vẫy đuôi tăng một trăm phần trăm." },
    "pet-thanks": { kind: "Đúng rồi! Đuôi mình vừa tự bật chế độ tăng tốc.", sassy: "Vuốt ve năm sao. Shiba duyệt, không sửa." },
    "drag-start": { kind: "Ui chao—nhớ giữ mình nhẹ tay nhé.", sassy: "Hãng hàng không Shiba đã cất cánh." },
    "drag-release": { kind: "Hạ cánh an toàn! Mình thích chỗ này.", sassy: "Đã chiếm vị trí. Đuôi xác nhận." },
    dismiss: { kind: "Được thôi! Mình nhường chỗ cho bạn.", sassy: "Rút lui đầy phẩm giá cùng một tiếng gâu bé xíu." },
    "less-of-this": { kind: "Mình nghe rồi. Trò đó sẽ ít hơn nhé.", sassy: "Cất trò đó về hộp đồ chơi thôi." },
    snoozed: { kind: "Nghỉ ngủ nào! Lát nữa mình quay lại.", sassy: "Đã nhận báo lại. Bắt đầu chạy vòng vòng trong mơ." },
    "manual-summon": { kind: "Bạn gọi! Mình chạy tới trước khi nghe hết câu.", sassy: "Giao Shiba hỏa tốc hoàn tất. Không nhận hoàn hàng." },
    "meeting-mode": { kind: "Đã bật Chế độ họp. Mình sẽ thật yên lặng.", sassy: "Đã dựng đôi tai nghiêm túc. Không gâu." },
    goodbye: { kind: "Tạm biệt! Nhớ nghỉ một chút nhé.", sassy: "Shiba rời sóng. Đuôi vẫn hoạt động tốt." }
  }
} as const satisfies LocaleDialogue;
